language: go
sudo: false
go: 1.6.3
os: osx
notifications:
  email: false
branches:
  except:
    - gh-pages
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  files:
    - 'build/smartling-darwin-386.tar.gz'
    - 'build/smartling-darwin-amd64.tar.gz'
    - 'build/smartling-linux-386.tar.gz'
    - 'build/smartling-linux-amd64.tar.gz'
  skip_cleanup: true
  on:
    tags: true
before_install:
  - brew update
  - brew install glide
  - glide --version
install:
  - make restore
script:
  - make clean
  - make lint
  - make coveralls
  - make build-all
