language: go
sudo: false
go: "1.10"
os: linux
notifications:
  email: false
branches:
  except:
    - gh-pages
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file:
    - 'build/smartling-$TRAVIS_TAG-darwin-386.tar.gz'
    - 'build/smartling-$TRAVIS_TAG-darwin-386.zip'
    - 'build/smartling-$TRAVIS_TAG-darwin-amd64.tar.gz'
    - 'build/smartling-$TRAVIS_TAG-darwin-amd64.zip'
    - 'build/smartling-$TRAVIS_TAG-freebsd-386.tar.gz'
    - 'build/smartling-$TRAVIS_TAG-freebsd-386.zip'
    - 'build/smartling-$TRAVIS_TAG-freebsd-amd64.tar.gz'
    - 'build/smartling-$TRAVIS_TAG-freebsd-amd64.zip'
    - 'build/smartling-$TRAVIS_TAG-linux-386.tar.gz'
    - 'build/smartling-$TRAVIS_TAG-linux-386.zip'
    - 'build/smartling-$TRAVIS_TAG-linux-amd64.tar.gz'
    - 'build/smartling-$TRAVIS_TAG-linux-amd64.zip'
    - 'build/smartling-$TRAVIS_TAG-linux-arm64.tar.gz'
    - 'build/smartling-$TRAVIS_TAG-linux-arm64.zip'
    - 'build/smartling-$TRAVIS_TAG-netbsd-386.tar.gz'
    - 'build/smartling-$TRAVIS_TAG-netbsd-386.zip'
    - 'build/smartling-$TRAVIS_TAG-netbsd-amd64.tar.gz'
    - 'build/smartling-$TRAVIS_TAG-netbsd-amd64.zip'
    - 'build/smartling-$TRAVIS_TAG-openbsd-386.tar.gz'
    - 'build/smartling-$TRAVIS_TAG-openbsd-386.zip'
    - 'build/smartling-$TRAVIS_TAG-openbsd-amd64.tar.gz'
    - 'build/smartling-$TRAVIS_TAG-openbsd-amd64.zip'
    - 'build/smartling-$TRAVIS_TAG-windows-386.tar.gz'
    - 'build/smartling-$TRAVIS_TAG-windows-386.zip'
    - 'build/smartling-$TRAVIS_TAG-windows-amd64.tar.gz'
    - 'build/smartling-$TRAVIS_TAG-windows-amd64.zip'
  skip_cleanup: true
  on:
    tags: true
cache:
  directories:
    - $GOPATH/pkg/dep
env:
  global:
    - DEP_VERSION=0.4.1
    - CC_VERSION=0.5.1
before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-${CC_VERSION}-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
install:
  - make deps
before_script:
  - ./cc-test-reporter before-build
script:
  - make clean
  - make lint
  - make cover
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ -n "$TRAVIS_TAG" ]; then make build-all pack-all; fi'
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
